const KIDSdb = [
["animal", "noun", [3], "動物"],
   ["bear", "noun", [3], "熊"],
   ["bee", "noun", [3], "蜜蜂"],
   ["bird", "noun", [3], "鳥"],
   ["bite", "verb", [3], "咬"],
   ["butterfly", "noun", [3], "蝴蝶"],
   ["cat", "noun", [3], "貓"],
   ["cow", "noun", [3], "乳牛"],
   ["dog", "noun", [3], "狗"],
   ["duck", "noun", [3], "鴨子"],
   ["elephant", "noun", [3], "大象"],
   ["frog", "noun", [3], "青蛙"],
   ["hippo", "noun", [3], "河馬"],
   ["horse", "noun", [3], "馬"],
   ["koala", "noun", [3], "無尾熊"],
   ["lion", "noun", [3], "獅子"],
   ["monkey", "noun", [3], "猴子"],
   ["mouse", "noun", [3], "老鼠"],
   ["mice", "noun", [3], "老鼠"],
   ["panda", "noun", [3], "大貓熊"],
   ["pet", "noun", [3], "寵物"],
   ["pig", "noun", [3], "豬"],
   ["rabbit", "noun", [3], "兔子"],
   ["sheep", "noun", [3], "綿羊"],
   ["snake", "noun", [3], "蛇"],
   ["spider", "noun", [3], "蜘蛛"],
   ["tiger", "noun", [3], "老虎"],
   ["turtle", "noun", [3], "烏龜"],
   ["whale", "noun", [3], "鯨魚"],
   ["zebra", "noun", [3], "斑馬"],
   ["chicken", "noun", [3, 7], "雞、雞肉"],
   ["fish","noun / verb", [3, 7, 23], "魚、魚肉(n.) / 釣魚(v.)"],
   ["a", "art.", [24], "一個"],
   ["an", "art.", [24], "一個"],
   ["every", "det.", [24], "每一個"],
   ["her", "det.", [24], "她的"],
   ["his", "det.", [24], "他的"],
   ["its", "det.", [24], "它的、牠的"],
   ["my", "det.", [24], "我的"],
   ["our", "det.", [24], "我們的"],
   ["that", "det.", [24], "那個(那些)"],
   ["those", "det.", [24], "那個(那些)"],
   ["this", "det.", [24], "這個(這些)"],
   ["the", "art.", [24], "這"],
   ["their", "det.", [24], "他們的"],
   ["these", "det.", [24], "這個(這些)"],
   ["your", "det.", [24], "你的、你們的"],
   ["is", "aux.", [24], "是"],
   ["am", "aux.", [24], "是"],
   ["are", "aux.", [24], "是"],
   ["be", "aux.", [24], "是"],
   ["will", "aux.", [24], "將會"],
   ["can", "aux. / noun", [24, 16, 30], "可以(aux.) / 罐子(n.)"],
   ["do", "aux. / verb", [24, 16, 31], "助動詞 / 做(v.)"],
   ["have", "aux. / verb", [24, 16, 31], "助動詞 / 有(v.)"],
   ["bag", "noun", [4], "袋子"],
   ["cap", "noun", [4], "棒球帽"],
   ["clothes", "noun", [4], "衣服"],
   ["coat", "noun", [4], "外套"],
   ["dress", "noun", [4], "洋裝"],
   ["glasses", "noun", [4], "眼鏡"],
   ["hat", "noun", [4], "帽子"],
   ["jacket", "noun", [4], "夾克外套"],
   ["pants", "noun", [4], "長褲"],
   ["pocket", "noun", [4], "口袋"],
   ["shirt", "noun", [4], "襯衫"],
   ["shoes", "noun", [4], "鞋子"],
   ["shorts", "noun", [4], "短褲"],
   ["skirt", "noun", [4], "裙子"],
   ["socks", "noun", [4], "襪子"],
   ["sweater", "noun", [4], "毛衣"],
   ["T-shirt", "noun", [4], "T 恤"],
   ["umbrella", "noun", [4], "傘"],
   ["wear", "verb", [4], "穿、戴"],
   ["black", "adj.", [5], "黑色的"],
   ["blue", "adj.", [5], "藍色的"],
   ["brown", "adj.", [5], "咖啡色的"],
   ["color", "noun", [5], "顏色"],
   ["gray", "adj.", [5], "灰色的"],
   ["green", "adj.", [5], "綠色的"],
   ["pink", "adj.", [5], "粉紅色的"],
   ["purple", "adj.", [5], "紫色的"],
   ["red", "adj.", [5], "紅色的"],
   ["white", "adj.", [5], "白色的"],
   ["yellow", "adj.", [5], "黃色的"],
   ["orange", "adj. / noun", [5, 7], "橘色的(adj.) / 橘子(n.)"],
   ["and", "conj.", [24], "和"],
   ["because", "conj.", [24], "因為"],
   ["but", "conj.", [24], "但是"],
   ["aunt", "noun", [6], "阿姨、姑姑、伯母、舅媽"],
   ["brother, ", noun, [6], "哥哥、弟弟"],
   ["cousin", "noun", [6], "堂兄（弟、姊、妹）"],
   ["daughter", "noun", [6], "女兒"],
   ["family", noun, [6], "家庭、家人"],
   ["father", "noun", [6], "爸爸"],
   ["dad", "noun", [6], "爸爸"],
   ["grandfather", "noun", [6], "外公、爺爺"],
   ["daddy", "noun", [6], "爸爸"],
   ["grandpa", "noun", [6], "外公、爺爺"],
   ["grandm16, ", noun, [6], "外婆、奶奶"],
   ["grandma", "noun", [6], "外婆、奶奶"],
   ["grow", "verb", [6], "成長、長大"],
   ["live", "verb", [6], "住"],
   ["mother, ", noun, [6], "媽媽"],
   ["mom", "noun", [6], "媽媽"],
   ["mommy", "noun", [6], "媽媽"],
   ["parent", "noun", [6], "父母親"],
   ["sister", "noun", [6], "姐姐、妹妹"],
   ["son", "noun", [6], "兒子"],
   ["uncle", "noun", [6], "叔叔、舅舅、姑丈、姨丈"],
   ["apple", "noun", [7], "蘋果"],
   ["banana", "noun", [7], "香蕉"],
   ["beef", "noun", [7], "牛肉"],
   ["bread", "noun", [7], "麵包"],
   ["breakfast", "noun", [7], "早餐"],
   ["cake", "noun", [7], "蛋糕"],
   ["candy", "noun", [7], "糖果"],
   ["chocolate", "noun", [7], "巧克力"],
   ["coffee", "noun", [7], "咖啡"],
   ["cola", "noun", [7], "可樂"],
   ["cookies", "noun", [7], "餅乾"],
   ["dinner", "noun", [7], "晚餐"],
   ["drink", "noun", [7], "喝"],
   ["dumpling", "noun", [7], "水餃"],
   ["eat", "verb", [7], "吃"],
   ["egg", "noun", [7], "蛋"],
   ["food", "noun", [7], "食物"],
   ["French fries", "noun", [7], "薯條"],
   ["fruit", "noun", [7], "水果"],
   ["full", "adj.", [7], "飽的"],
   ["grape", "noun", [7], "葡萄"],
   ["hamburger", "noun", [7], "漢堡"],
   ["hungry", "adj.", [7], "餓的"],
   ["ice cream", "noun", [7], "冰淇淋"],
   ["juice", "noun", [7], "果汁"],
   ["lemon", "noun", [7], "檸檬"],
   ["lunch", "noun", [7], "午餐"],
   ["meal", "noun", [7], "餐"],
   ["milk", "noun", [7], "牛奶"],
   ["noodles", "noun", [7], "麵"],
   ["peach", "noun", [7], "桃子"],
   ["pie", "noun", [7], "派"],
   ["pizza", "noun", [7], "披薩"],
   ["pork", "noun", [7], "豬肉"],
   ["pumpkin", "noun", [7], "南瓜"],
   ["rice", "noun", [7], "米飯"],
   ["salad", "noun", [7], "沙拉"],
   ["sandwich", "noun", [7], "三明治"],
   ["soup", "noun", [7], "湯"],
   ["strawberry", "noun", [7], "草莓"],
   ["sweet", "adj.", [7], "甜的"],
   ["tea", "noun", [7], "茶"],
   ["thirsty", "adj.", [7], "口渴的"],
   ["water", "noun", [7], "水"],
   ["watermelon", "noun", [7], "西瓜"],
   ["yummy", "adj.", [7], "好吃的、美味的"],
   ["cook", "noun / verb", [7, 15], "廚師(n.) / 做飯(v.)"],
   ["Miss", "noun", [8], "小姐"],
   ["Mr.", "noun", [8], "先生"],
   ["Mrs.", "noun", [8], "太太"],
   ["name", "noun", [8], "名字"],
   ["beach", "noun", [9], "海灘"],
   ["lake", "noun", [9], "湖"],
   ["mountain", "noun", [9], "山"],
   ["river", "noun", [9], "河流"],
   ["sea", "noun", [9], "大海"],
   ["headache", "noun", [10], "頭痛"],
   ["sick", "adj.", [10], "生病的"],
   ["strong", "adj.", [10], "強壯的"],
   ["tired", "adj.", [10], "疲累的"],
   ["toothache", "noun", [10], "牙痛"],
   ["well", "adj. / adv.", [10], "好的(adj.) / 健康地(adv.)"],
   ["Chinese New Year", "noun", [11], "農曆新年"],
   ["Lantern Festival", "noun", [11], "元宵節"],
   ["Moon Festival", "noun", [11], "中秋節"],
   ["Dragon Boat Festival", "noun", [11], "端午節"],
   ["Christmas", "noun", [11], "聖誕節"],
   ["Halloween", "noun", [11], "萬聖節"],
   ["celebrate", "verb", [11], "慶祝"],
   ["bathroom", "noun", [12], "浴室"],
   ["bed", "noun", [12], "床"],
   ["bedroom", "noun", [12], "臥房"],
   ["chair", "noun", [12], "椅子"],
   ["clean", "adj. / verb", [12], "乾淨的(adj.) / 清理(v.)"],
   ["computer", "noun", [12], "電腦"],
   ["desk", "noun", [12], "桌子"],
   ["dining room", "noun", [12], "(家裡的)餐廳"],
   ["door", "noun", [12], "門"],
   ["fan", "noun", [12], "電扇"],
   ["floor", "noun", [12], "地板"],
   ["garden", "noun", [12], "院子、花園"],
   ["home", "noun", [12], "家庭"],
   ["house", "noun", [12], "房子"],
   ["key", "noun", [12], "鑰匙"],
   ["kitchen", "noun", [12], "廚房"],
   ["lamp", "noun", [12], "燈"],
   ["living room", "noun", [12], "客廳"],
   ["refrigerator", "noun", [12], "電冰箱"],
   ["fridge", "noun", [12], "電冰箱"],
   ["shelf", "noun", [12], "架子"],
   ["shower", "noun", [12], "淋浴"],
   ["sofa", "noun", [12], "沙發"],
   ["street", "noun", [12], "街道"],
   ["sweep", "verb", [12], "掃"],
   ["table", "noun", [12], "桌子"],
   ["telephone", "noun", [12], "電話"],
   ["towel", "noun", [12], "毛巾"],
   ["TV", "noun", [12], "電視"],
   ["television", "noun", [12], "電視"],
   ["wall", "noun", [12], "牆壁"],
   ["wash", "verb", [12], "洗"],
   ["window", "noun", [12], "窗戶"],
   ["excuse me", "interj.", [16], "不好意思、對不起"],
   ["bye", "interj.", [16], "再見"],
   ["goodbye", "interj.", [16], "再見"],
   ["hi", "interj.", [16], "哈囉、嗨"],
   ["hello", "interj.", [16], "哈囉、嗨"],
   ["please", "interj.", [16], "請"],
   ["buy", "verb", [13], "買"],
   ["dollar", "noun", [13], "元"],
   ["free", "adj.", [13], "免費的"],
   ["money", "noun", [13], "錢"],
   ["all", "det.", [14], "全部的"],
   ["both", "det.", [14], "兩個都"],
   ["eight", "num.", [14], "八"],
   ["eighteen", "num.", [14], "十八"],
   ["eighty", "num.", [14], "八十"],
   ["eleven", "num.", [14], "十一"],
   ["fifteen", "num.", [14], "十五"],
   ["fifty", "num.", [14], "五十"],
   ["first", "num.", [14], "第一"],
   ["five", "num.", [14], "五"],
   ["forty", "num.", [14], "四十"],
   ["four", "num.", [14], "四"],
   ["fourteen", "num.", [14], "十四"],
   ["hundred", "num.", [14], "一百"],
   ["last", "det. / adj.", [14], "最後的"],
   ["many", "det. / adj.", [14], "許多(例如many flowers)"],
   ["more", "det. / adv.", [14], "更多、較多"],
   ["much", "det. / adv.", [14], "許多(例如much water)"],
   ["nine", "num.", [14], "九"],
   ["nineteen", "num.", [14], "十九"],
   ["ninety", "num.", [14], "九十"],
   ["number", "noun", [14], "數字"],
   ["one", "num.", [14], "一"],
   ["second", "num.", [14], "第二"],
   ["seven", "num.", [14], "七"],
   ["seventeen", "num.", [14], "十七"],
   ["seventy", "num.", [14], "七十"],
   ["six", "num.", [14], "六"],
   ["sixteen", "num.", [14], "十六"],
   ["sixty", "num.", [14], "六十"],
   ["some", "det.", [14], "一些"],
   ["ten", "num.", [14], "十"],
   ["third", "num.", [14], "第三"],
   ["thirteen", "num.", [14], "十三"],
   ["thirty", "num.", [14], "三十"],
   ["three", "num.", [14], "三"],
   ["twelve", "num.", [14], "十二"],
   ["twenty", "num.", [14], "二十"],
   ["two", "num.", [14], "二"],
   ["zero", "num.", [14], "零"],
   ["actor", "noun", [15], "男演員 / 女演員"],
   ["actress", "noun", [15], "男演員 / 女演員"],
   ["doctor", "noun", [15], "醫生"],
   ["driver", "noun", [15], "司機、駕駛員"],
   ["farmer", "noun", [15], "農夫"],
   ["job", "noun", [15], "工作、職業"],
   ["mailman", "noun", [15], "郵差"],
   ["nurse", "noun", [15], "護士"],
   ["police officer", "noun", [15], "警察"],
   ["singer", "noun", [15], "歌手"],
   ["soldier", "noun", [15], "軍人"],
   ["waitress", "noun", [15], "服務生"],
   ["waiter", "noun", [15], "服務生"],
   ["work", "noun", [15], "工作"],
   ["worker", "noun", [15], "工作者"],
   ["different", "adj.", [16], "不一樣的"],
   ["dirty", "adj.", [16], "髒的"],
   ["easy", "adj.", [16], "簡單的"],
   ["favorite", "adj.", [16], "最喜歡的"],
   ["fine", "adj.", [16], "很好的、很不錯的"],
   ["great", "adj.", [16], "很棒的"],
   ["hard", "adj.", [16], "困難的"],
   ["interesting", "adj.", [16], "有趣的"],
   ["new", "adj.", [16], "新的"],
   ["other", "det. / pron. / adj.", [16], "其他的"],
   ["quiet", "adj.", [16], "安靜的"],
   ["ready", "adj.", [16], "準備好的"],
   ["sorry", "adj.", [16], "感到抱歉的、對不起"],
   ["wonderful", "adj.", [16], "很棒的、精彩的"],
   ["OK", "adj. / adv.", [16], "好的(adj.) / 沒事(adv.)"],
   ["only", "adj. / adv.", [16], "僅有的 / 唯一地"],
   ["sure", "adj. / adv.", [16], "確定的(adj.) / 當然(adv.)"],
   ["right", "adj.", [16, 20], "1. 對的；2. 右邊"],
   ["again", "adv.", [16], "再一次、又一次"],
   ["always", "adv.", [16], "總是、永遠"],
   ["away", "adv.", [16], "離開"],
   ["maybe", "adv.", [16], "也許"],
   ["never", "adv.", [16], "不曾"],
   ["no", "adv.", [16], "不"],
   ["not", "adv.", [16], "不、沒有"],
   ["really", "adv.", [16], "真正地"],
   ["so", "adv.", [16], "所以"],
   ["sometime", s", [adv.], "16, ", "有時候"],
   ["still", "adv.", [16], "仍然"],
   ["then", "adv.", [16], "然後、接著"],
   ["together", "adv.", [16], "一起"],
   ["too", "adv.", [16], "1. 也, 2. 太…"],
   ["usually", "adv.", [16], "通常"],
   ["very", "adv.", [16], "非常"],
   ["yes", "adv.", [16], "是"],
   ["birthday", "noun", [16], "生日"],
   ["bottle", "noun", [16], "瓶子"],
   ["box", "noun", [16], "箱子"],
   ["cellphone", "noun", [16], "手機"],
   ["dream", "noun", [16], "夢"],
   ["e-mail", "noun", [16], "電子郵件"],
   ["email", "noun", [16], "電子郵件"],
   ["flower", "noun", [16], "花"],
   ["fun", "adj. / noun", [16], "有趣的(adj.) / 樂趣(n.)"],
   ["gift", "noun", [16], "禮物"],
   ["mail", "noun", [16], "信"],
   ["party", "noun", [16], "派對"],
   ["photo", "noun", [16], "照片"],
   ["robot", "noun", [16], "機器人"],
   ["sale", "noun", [16], "拍賣、特價"],
   ["thing", "noun", [16], "東西、物"],
   ["ticket", "noun", [16], "票"],
   ["trash", "noun", [16], "垃圾"],
   ["tree", "noun", [16], "樹"],
   ["way", "noun", [16], "路、方向"],
   ["word", "noun", [16], "字"],
   ["brush", "verb", [16], "用刷子刷"],
   ["call", "verb", [16], "打電話給…"],
   ["close", "verb", [16], "關"],
   ["come", "verb", [16], "來"],
   ["cry", "verb", [16], "哭、哭泣"],
   ["enjoy", "verb", [16], "享受、喜歡"],
   ["feel", "verb", [16], "感受、感覺"],
   ["find", "verb", [16], "找"],
   ["get", "verb", [16], "得到、收到"],
   ["give", "verb", [16], "給"],
   ["go", "verb", [16], "去、走"],
   ["help", "verb", [16], "幫助"],
   ["hit", "verb", [16], "打、碰撞"],
   ["hope", "verb", [16], "希望"],
   ["hurry", "verb", [16], "趕快、急忙"],
   ["hurt", "verb", [16], "受傷"],
   ["jump", "verb", [16], "跳"],
   ["know", "verb", [16], "知道、認識"],
   ["laugh", "verb", [16], "笑"],
   ["let's", "verb", [16], "讓我們…"],
   ["like", "verb", [16], "喜歡"],
   ["look", "verb", [16], "看、看起來"],
   ["love", "verb", [16], "愛、喜愛"],
   ["make", "verb", [16], "做、製造"],
   ["meet", "verb", [16], "遇見、會面"],
   ["miss", "verb", [16], "想念"],
   ["mop", "verb", [16], "用拖把拖地"],
   ["need", "verb", [16], "需要"],
   ["open", "verb", [16], "開"],
   ["pick up", "verb", [16], "撿起、接（人）、接（電話）"],
   ["put", "verb", [16], "放"],
   ["see", "verb", [16], "看見"],
   ["show", "verb", [16], "給...看、展示"],
   ["sit", "verb", [16], "坐下"],
   ["sleep", "verb", [16], "睡覺"],
   ["smell", "verb", [16], "聞起來"],
   ["stand", "verb", [16], "站、站立"],
   ["start", "verb", [16], "開始"],
   ["stop", "verb", [16], "停下來"],
   ["take", "verb", [16], "攜帶、拿取"],
   ["taste", "verb", [16], "嚐起來"],
   ["tell", "verb", [16], "告訴、告知"],
   ["thank", "verb", [16], "感謝（某人）"],
   ["touch", "verb", [16], "觸碰"],
   ["try", "verb", [16], "嘗試"],
   ["wait", "verb", [16], "等、等待"],
   ["wake", "verb", [16], "醒來、喚醒"],
   ["walk", "verb", [16], "走路"],
   ["want", "verb", [16], "想要"],
   ["welcome", "verb", [16], "歡迎"],
   ["worry", "verb", [16], "擔心"],
   ["arm", "noun", [17], "手臂"],
   ["ear", "noun", [17], "耳朵"],
   ["eye", "noun", [17], "眼睛"],
   ["face", "noun", [17], "臉"],
   ["foot", "noun", [17], "腳"],
   ["feet", "noun", [17], "腳"],
   ["hair", "noun", [17], "頭髮"],
   ["hand", "noun", [17], "手"],
   ["head", "noun", [17], "頭"],
   ["leg", "noun", [17], "腿"],
   ["mouth", "noun", [17], "嘴巴"],
   ["nose", "noun", [17], "鼻子"],
   ["tooth", "noun", [17], "牙齒"],
   ["teeth", "noun", [17], "牙齒"],
   ["back","noun / adv.", [17, 20], "背(n.) / 向後、回原處(adv.)"],
   ["baby", "noun", [18], "嬰兒"],
   ["boy", "noun", [18], "男孩"],
   ["girl", "noun", [18], "女孩"],
   ["kid", "noun", [18], "小孩"],
   ["men", "noun", [18], "男人"],
   ["many", "noun", [18], "男人"],
   ["person", "noun", [18], "人"],
   ["people", "noun", [18], "人"],
   ["woman", "noun", [18], "女人"],
   ["women", "noun", [18], "女人"],
   ["angry", "adj.", [19], "生氣的"],
   ["bad", "adj.", [19], "不好的、壞的"],
   ["beautiful", "adj.", [19], "美麗的、漂亮的"],
   ["bored", "adj.", [19], "覺得無聊的"],
   ["boring", "adj.", [19], "令人無聊的"],
   ["busy", "adj.", [19], "忙碌的"],
   ["cute", "adj.", [19], "可愛的"],
   ["excited", "adj.", [19], "覺得興奮的"],
   ["exciting", "adj.", [19], "令人興奮的"],
   ["good", "adj.", [19], "好的"],
   ["happy", "adj.", [19], "開心的、高興的"],
   ["lazy", "adj.", [19], "懶惰的"],
   ["mad", "adj.", [19], "生氣的、氣憤的"],
   ["nice", "adj.", [19], "令人愉快的、宜人的"],
   ["old", "adj.", [19], "1. 年紀、年齡；2. 老的"],
   ["pretty", "adj.", [19], "漂亮的"],
   ["sad", "adj.", [19], "傷心的、難過的"],
   ["smart", "adj.", [19], "聰明的"],
   ["tall", "adj.", [19], "高的"],
   ["thin", "adj.", [19], "瘦的"],
   ["young", "adj.", [19], "年輕的"],
   ["heavy", "adj.", [19, 22], "重的"],
   ["short","adj.","19, 22, ","矮的、短的"],
   ["bank", "noun", [20], "銀行"],
   ["bookstore", "noun", [20], "書店"],
   ["department store", "noun", [20], "百貨公司"],
   ["fire station", "noun", [20], "消防站"],
   ["here", "adv.", [20], "這裡"],
   ["hospital", "noun", [20], "醫院"],
   ["left", "adj. / adv.", [20], "左邊(的)"],
   ["market", "noun", [20], "市場"],
   ["movie theater", "noun", [20], "電影院"],
   ["museum", "noun", [20], "博物館"],
   ["office", "noun", [20], "辦公室"],
   ["park", "noun", [20], "公園"],
   ["police station", "noun", [20], "警察局"],
   ["post office", "noun", [20], "郵局"],
   ["restaurant", "noun", [20], "餐廳"],
   ["restroom", "noun", [20], "洗手間、廁所"],
   ["shop", "noun", [20], "商店"],
   ["store", "noun", [20], "商店"],
   ["supermarket", "noun", [20], "超級市場"],
   ["there", "adv.", [20], "那裡"],
   ["zoo", "noun", [20], "動物園"],
   ["Taiwan", "noun", [20], "臺灣"],
   ["Japan", "noun", [20], "日本"],
   ["UK", "noun", [20], "英國"],
   ["USA", "noun", [20], "美國"],
   ["about", "prep.", [24], "1. 大約；2. 關於…"],
   ["after", "prep.", [24], "在…之後"],
   ["at", "prep.", [24], "在(某處)、在(時刻)"],
   ["before", "prep. / conj.", [24], "在…之前"],
   ["behind", "prep.", [24], "在…後面"],
   ["by", "prep.", [24], "在…旁邊"],
   ["for", "prep.", [24], "給、為了(某人、物)"],
   ["from", "prep.", [24], "從(某處) / (某時刻) / (某人)"],
   ["in", "prep.", [24], "在…裡面、在某短時間裡"],
   ["in front of", "prep.", [24], "在…前面"],
   ["inside", "prep.", [24], "在…裡面、向…裡面"],
   ["near", "prep.", [24], "靠近、接近"],
   ["next to", "prep.", [24], "在…旁邊"],
   ["of", "prep.", [24], "…的"],
   ["off", "prep.", [24], "離開、從…去掉"],
   ["on", "prep.", [24], "在…上面；在(某一天)"],
   ["out", "prep.", [24], "向外地"],
   ["outside", "prep.", [24], "在…外面、向…外面"],
   ["over", "prep.", [24], "在…上方"],
   ["than", "prep.", [24], "比"],
   ["to", "prep.", [24], "向、朝、對著"],
   ["under", "prep.", [24], "在…下方"],
   ["up", "prep.", [24], "向上"],
   ["with", "prep.", [24], "和…一起"],
   ["he", "pron.", [24], "他"],
   ["him", "pron.", [24], "他(受詞)"],
   ["I", "pron.", [24], "我"],
   ["it", "pron.", [24], "它、牠"],
   ["me", "pron.", [24], "我(受詞)"],
   ["mine", "pron.", [24], "我的(所有格代名詞)"],
   ["nothing", "pron.", [24], "什麼都沒有"],
   ["she", "pron.", [24], "她"],
   ["them", "pron.", [24], "他們(受詞)"],
   ["they", "pron.", [24], "他們"],
   ["us", "pron.", [24], "我們(受詞)"],
   ["we", "pron.", [24], "我們"],
   ["you", "pron.", [24], "你；你們"],
   ["answer", "verb", [21], "回答"],
   ["art", "noun", [21], "美術、藝術"],
   ["ask", "verb", [21], "問"],
   ["blackboard", "noun", [21], "黑板"],
   ["book", "noun", [21], "書、書本"],
   ["Chinese", "noun", [21], "中文"],
   ["class", "noun", [21], "課；班級"],
   ["classroom", "noun", [21], "教室"],
   ["draw", "verb", [21], "畫、描畫"],
   ["English", "noun", [21], "英文"],
   ["eraser", "noun", [21], "橡皮擦"],
   ["friend", "noun", [21], "朋友"],
   ["glue", "noun", [21], "膠水"],
   ["homework", "noun", [21], "回家作業"],
   ["library", "noun", [21], "圖書館"],
   ["listen", "verb", [21], "聽"],
   ["marker", "noun", [21], "麥克筆"],
   ["math", "noun", [21], "數學"],
   ["music", "noun", [21], "音樂"],
   ["paper", "noun", [21], "紙張"],
   ["PE", "noun", [21], "體育（課）"],
   ["pen", "noun", [21], "筆、鋼筆"],
   ["pencil", "noun", [21], "鉛筆"],
   ["picture", "noun", [21], "圖片、照片"],
   ["question", "noun", [21], "問題"],
   ["read", "verb", [21], "閱讀"],
   ["ruler", "noun", [21], "尺"],
   ["say", "verb", [21], "說"],
   ["school", "noun", [21], "學校"],
   ["science", "noun", [21], "科學"],
   ["speak", "verb", [21], "說"],
   ["spell", "verb", [21], "拼寫、用字母拼"],
   ["story", "noun", [21], "故事"],
   ["student", "noun", [21], "學生"],
   ["study", "verb", [21], "學習"],
   ["talk", "verb", [21], "說話、談話"],
   ["teacher", "noun", [21], "老師"],
   ["test", "noun", [21], "考試"],
   ["vacation", "noun", [21], "假期"],
   ["write", "verb", [21], "寫"],
   ["big", "adj.", [22], "大的"],
   ["high", "adj.", [22], "高的"],
   ["light", "adj.", [22], "輕的"],
   ["long", "adj.", [22], "長的"],
   ["pair", "noun", [22], "一雙、一對"],
   ["small", "adj.", [22], "小的"],
   ["ball", "noun", [23], "球"],
   ["baseball", "noun", [23], "棒球"],
   ["basketball", "noun", [23], "籃球"],
   ["card", "noun", [23], "卡片"],
   ["climb", "verb", [23], "爬、攀爬"],
   ["dance", "verb", [23], "跳舞"],
   ["doll", "noun", [23], "玩偶"],
   ["drum", "noun", [23], "鼓"],
   ["game", "noun", [23], "遊戲、比賽"],
   ["hike", "verb", [23], "健行"],
   ["kite", "noun", [23], "風箏"],
   ["movie", "noun", [23], "電影"],
   ["paint", "verb", [23], "用顏料畫、刷油漆"],
   ["piano", "noun", [23], "鋼琴"],
   ["play", "verb", [23], "玩"],
   ["run", "verb", [23], "跑、跑步"],
   ["sing", "verb", [23], "唱歌"],
   ["soccer", "noun", [23], "足球"],
   ["football", "noun", [23], "足球"],
   ["song", "noun", [23], "歌曲"],
   ["sport", "noun", [23], "運動"],
   ["swim", "verb", [23], "游泳"],
   ["toy", "noun", [23], "玩具"],
   ["trip", "noun", [23], "（短程的）旅行"],
   ["win", "verb", [23], "贏"],
   ["yo-yo", "noun", [23], "溜溜球"],
   ["chopsticks", "noun", [25], "筷子"],
   ["cup", "noun", [25], "杯子"],
   ["dish", "noun", [25], "碟子、盤子"],
   ["fork", "noun", [25], "叉子"],
   ["glass", "noun", [25], "玻璃杯"],
   ["knife", "noun", [25], "刀子"],
   ["spoon", "noun", [25], "湯匙"],
   ["afternoon", "noun", [26], "下午"],
   ["April", "noun", [26], "四月"],
   ["August", "noun", [26], "八月"],
   ["clock", "noun", [26], "時鐘"],
   ["day", "noun", [26], "天"],
   ["December", "noun", [26], "十二月"],
   ["early", "adj. / adv.", [26], "早到（的）"],
   ["evening", "noun", [26], "傍晚"],
   ["February", "noun", [26], "二月"],
   ["Friday", "noun", [26], "星期五"],
   ["January", "noun", [26], "一月"],
   ["July", "noun", [26], "七月"],
   ["June", "noun", [26], "六月"],
   ["late", "adj. / adv.", [26], "晚到（的）"],
   ["March", "noun", [26], "三月"],
   ["May", "noun", [26], "五月"],
   ["Monday", "noun", [26], "星期一"],
   ["month", "noun", [26], "月"],
   ["morning", "noun", [26], "早上"],
   ["night", "noun", [26], "晚上"],
   ["November", "noun", [26], "十一月"],
   ["now", "adv.", [26], "現在"],
   ["o'clock", "adv.", [26], "…點鐘"],
   ["October", "noun", [26], "十月"],
   ["Saturday", "noun", [26], "星期六"],
   ["season", "noun", [26], "季節"],
   ["September", "noun", [26], "九月"],
   ["spring", "noun", [26], "春天"],
   ["summer", "noun", [26], "夏天"],
   ["Sunday", "noun", [26], "星期日"],
   ["Thursday", "noun", [26], "星期四"],
   ["time", noun, [26], "時間"],
   ["today", "noun", [26], "今天"],
   ["tomorrow", "noun", [26], "明天"],
   ["Tuesday", "noun", [26], "星期二"],
   ["Wednesday", "noun", [26], "星期三"],
   ["week", "noun", [26], "星期"],
   ["weekend", "noun", [26], "週末"],
   ["winter", "noun", [26], "冬天"],
   ["year", "noun", [26], "年"],
   ["yesterday", "noun", [26], "昨天"],
   ["fall", "noun / verb", [26, 16], "秋天(n.) / 掉落(v.)"],
   ["watch", "noun / verb", [26, 16], "手錶(n.) / 看(v.)"],
   ["airport", "noun", [27], "機場"],
   ["bike", "noun", [27], "腳踏車"],
   ["bicycle", "noun", [27], "腳踏車"],
   ["boat", "noun", [27], "船"],
   ["bus", "noun", [27], "公車"],
   ["bus stop", "noun", [27], "公車站"],
   ["car", "noun", [27], "車子"],
   ["drive", "verb", [27], "開車"],
   ["fast", "adj. / adv.", [27], "快速的（地）"],
   ["fly", "verb", [27], "飛、飛行"],
   ["motorcycle", "noun", [27], "摩托車"],
   ["MRT", "noun", [27], "捷運"],
   ["plane", "noun", [27], "飛機"],
   ["airplane", "noun", [27], "飛機"],
   ["ride", "verb", [27], "騎（機車、腳踏車等）"],
   ["scooter", "noun", [27], "小型摩托車"],
   ["ship", "noun", [27], "（大）船"],
   ["slow", "adj.", [27], "慢的"],
   ["taxi", "noun", [27], "計程車"],
   ["train", "noun", [27], "火車"],
   ["station", "noun", [27], "車站"],
   ["truck", "noun", [27], "卡車"],
   ["turn", "verb", [27], "轉彎"],
   ["cloudy", "adj.", [28], "多雲的"],
   ["moon", "noun", [28], "月亮"],
   ["rain", "noun / verb", [28], "雨水(n.) / 下雨(v.)"],
   ["rainbow", "noun", [28], "彩虹"],
   ["rainy", "adj.", [28], "下雨的"],
   ["sky", "noun", [28], "天空"],
   ["snow", "noun / verb", [28], "雪(n.) / 下雪(v.)"],
   ["star", "noun", [28], "星星"],
   ["sun", "noun", [28], "太陽"],
   ["sunny", "adj.", [28], "晴朗的、出太陽的"],
   ["typhoon", "noun", [28], "颱風"],
   ["warm", "adj.", [28], "溫暖的"],
   ["weather", "noun", [28], "天氣"],
   ["wind", "noun", [28], "風"],
   ["windy", "adj.", [28], "風大的"],
   ["cold","adj. / noun","28, 10, [,]寒冷的(adj.) / 感冒(n.)"],
   ["cool", "adj.", [28, 16], "涼爽的、清涼的"],
   ["hot", "adj.", [28, 16], "熱的、燙的"],
   ["wet", "adj.", [28, 16], "潮濕的、濕的"],
   ["how", "adv.", [29], "如何…"],
   ["what", "pron.", [29], "什麼…"],
   ["when", "adv.", [29], "何時…"],
   ["where", "adv.", [29], "在哪裡…"],
   ["which", "det.", [29], "哪一個…"],
   ["who", "pron.", [29], "誰…"],
   ["whose", "det.", [29], "誰的…"],
   ["why", "adv.", [29], "為什麼…"]
   ]