const levels = ["elementary",
  "intermediate",
  "high-intermediate",
  "Animals & insects",
  "Clothing & accessories",
  "Colors",
  "Family",
  "Food & drink",
  "Forms of address",
  "Geographical terms",
  "Health",
  "Holidays & festivals",
  "Houses & apartments",
  "Money",
  "Numbers",
  "Occupations",
  "Other",
  "Parts of body",
  "People",
  "Personal characteristics",
  "Places & directions",
  "School",
  "Sizes & measurements",
  "Sports, interest & hobbies",
  "Syntax",
  "Tableware",
  "Time",
  "Transportation",
  "Weather & nature",
  "Wh-words",
  "nouns",
  "verbs"]